name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Enable Corepack (For yarn)
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install and Build
        run: |
          yarn install --immutable
          yarn build
